# Usa una imagen base de PHP con Apache
FROM php:8.0-apache

# Copia el archivo PHP a la carpeta raíz del servidor web
COPY formulario.php /var/www/html/

# Exponer el puerto 80 para acceder al servidor web
EXPOSE 80

# Inicia el servidor Apache en el contenedor
CMD ["apache2-foreground"]
